name: Lint Documentation

on:
  pull_request:
    paths:
      - 'docs/**'  # Adjust this pattern as needed

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch docs-styles repository
        run: |
          git clone https://github.com/ivegabr/docs-styles.git ./docs-styles

      - name: Install Vale
        run: |
          curl -L https://install.goreleaser.com/github.com/errata-ai/vale.sh | sh
          # Add Vale to PATH if necessary (adjust the path if required)
          echo "${PWD}/vale" >> $GITHUB_PATH

      - name: Run Vale via reviewdog
        uses: reviewdog/action-vale@v1
        with:
          # Use GitHub's PR review to post comments
          reporter: github-pr-review
          # Fail the job if there are errors (set to false if you prefer warnings only)
          fail_on_error: true
          # Pass additional flags to Vale. Here, we point it to the docs folder and use the central config.
          vale_flags: "--config=./docs-styles/.vale.ini docs/"