name: Lint Documentation

on:
  [pull_request]
    # paths:
    #   - 'docs/**'  # Adjust this pattern as needed

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch docs-styles repository
        run: |
          git clone https://github.com/ivegabr/docs-styles.git ./docs-styles

      - name: Install Vale
        run: |
          curl -L https://install.goreleaser.com/github.com/errata-ai/vale.sh | sh
          # Add Vale to PATH if necessary (adjust the path if required)
          echo "${PWD}/vale" >> $GITHUB_PATH

      - name: Install reviewdog
        uses: reviewdog/action-setup@v1
        with:
            reviewdog_version: latest
        
      - name: Run Vale and report via reviewdog
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            # Run Vale using the central config and output results in JSON format.
            vale --output=JSON --config=./docs-styles/.vale.ini docs/ > vale-report.json
            # Pipe Vale's JSON output into reviewdog.
            # The '-f=rdjson' flag tells reviewdog to expect Reviewdog's JSON format.
            reviewdog -f=rdjson -name=vale -reporter=github-pr-review -level=error < vale-report.json